#! /bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PVER=3.13
PINC="-I${SCRIPT_DIR}/../tool-install/pack/include/python${PVER}"
PLD="-L${SCRIPT_DIR}/../tool-install/pack/lib -lpython${PVER}"
TINST="/root/pack"

if [ $# -ne 2 ]
then
        echo "Bad # args.  Blech!" >&2
        exit 1
fi

# The first argument is the path to python-config.py, ignore it.
case "$2" in
        --includes) echo ${PINC} ;;
        --ldflags) echo ${PLD} ;;
        --exec-prefix) echo ${TINST} ;;
        *) echo "Bad arg $2.  Blech!" >&2 ; exit 1 ;;
esac

exit 0
